# Generated by Django 2.1 on 2018-10-20 20:05

from django.db import migrations, models
import django.db.models.deletion
import maincore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255, validators=[maincore.models.is_valid_field])),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='models', to='maincore.App')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='settings', to='maincore.Field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fields', to='maincore.Model'),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('field', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='model',
            unique_together={('app', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('model', 'name')},
        ),
    ]
